services:
  mysql:
    image: mysql:5.7
    container_name: mysql_gnut
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gnut06
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
 
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_gnut
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql


  maildev:
    image: maildev/maildev
    container_name: maildev_gnut
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 1080:80
      - 1025:25
    restart: always

  symfony:
    build:
      context: ./app
    container_name: symfony_asso
    restart: always
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/gnut06?serverVersion=5.7&charset=utf8mb4"
    volumes:
      - ./app:/var/www/app
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      - mysql
    #command: php -S 0.0.0.0:8000 -t /var/www/app/public



volumes:
  mysql: