# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    helloasso.api_client_id: '%env(APICLIENTID)%'
    helloasso.api_client_secret: '%env(APICLIENTSECRET)%'
    mailjet.api_key: '%env(APIMAILJET)%'
    mailjet.api_secret: '%env(APIMAILJETSECRET)%'
    ohme.api_key: '%env(SECRETOHME)%'
    parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/profilePictures'
    bordereau_directory: '%kernel.project_dir%/public/uploads/bordereau'
    nocaptcha.secret: '%env(NOCAPTCHA_SECRET)%'
    nocaptcha.sitekey: '%env(NOCAPTCHA_SITEKEY)%'
    app.env: '%env(APP_ENV)%'
    

services:
    App\MessageHandler\NotificationHandler:
        tags: [messenger.message_handler]
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
          $slugAsso: '%env(SLUGASSO)%'
          $helloAssoApiClientId: '%env(APICLIENTID)%'
          $helloAssoApiClientSecret: '%env(APICLIENTSECRET)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Message/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\TokenManager:
        arguments:
            $clientId: '%env(APICLIENTID)%'
            $clientSecret: '%env(APICLIENTSECRET)%'
            $urlToken: 'https://api.helloasso.com/oauth2/token'
            $slugAsso: '%env(SLUGASSO)%'

    App\Service\HelloAssoAuthService:
        class: App\Service\HelloAssoAuthService
        arguments:
            - '@request_stack'
            - '%env(APICLIENTID)%'
            - '%env(APICLIENTSECRET)%'

    App\Service\HelloAssoApiService:
        class: App\Service\HelloAssoApiService
        arguments:
            $helloAssoAuthService: '@App\Service\HelloAssoAuthService'

    # Configuration spécifique pour votre service de pagination
    App\Service\PaginationService:
        class: App\Service\PaginationService
        arguments:
            $limit: 12 # Vous pouvez définir une valeur par défaut différente pour 'limit' ici si nécessaire

    App\Service\AssoRecommanderService:
        class: App\Service\AssoRecommanderService

    App\Service\DataFilterAndSortService:
        class: App\Service\DataFilterAndSortService

    App\Service\MailjetService:
        arguments:
            $apiKey: '%env(APIMAILJET)%'
            $apiSecret: '%env(APIMAILJETSECRET)%'

    App\Service\OhmeApiService:
        arguments:
            $slugAsso: '%env(SLUGASSO)%'
            $secretOhme: '%env(SECRETOHME)%'

    App\Service\ApiFrameVrService:
        arguments:
            $apiKey: '%env(APIFRAMEVR)%'
        
    App\Service\RecaptchaVerifier:
        arguments:
            $client: '@http_client'
            $secretKey: '%nocaptcha.secret%'
            $appEnv: '%app.env%'
            $recaptchaSecret: '%nocaptcha.secret%'

    App\Service\EmailService: ~
    
    App\Controller\RegistrationController:
        arguments:
            $recaptchaSecret: '%nocaptcha.secret%'
            $appEnv: '%app.env%'
